// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/akram/Documents/FOMO/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/akram/Documents/FOMO/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('fomo', appParameters);
});
require('c:/Users/akram/Documents/FOMO/index.js');